# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = '$all$fill$time$line_break$character'

[fill]
symbol = ' '

[time]
disabled = false
format = '[$time]($style)'

