return {
    "startup-nvim/startup.nvim",
    dependencies = { "nvim-telescope/telescope.nvim", "nvim-lua/plenary.nvim" },
    opts = {
        header = {
            type = "text",
            oldfiles_directory = false,
            align = "center",
            fold_section = false,
            title = "Header",
            margin = 5,
            content = {
                   "_,    _   _    ,_",
              ".o888P     Y8o8Y     Y888o.",
             "d88888      88888      88888b",
            "d888888b_  _d88888b_  _d888888b",
            "8888888888888888888888888888888",
            "8888888888888888888888888888888",
            "YJGS8P\"Y888P\"Y888P\"Y888P\"Y8888P",
             "Y888   '8'   Y8P   '8'   888Y",
              "'8o          V          o8'",
                "`                     `",
            },
            highlight = "Statement",
            default_color = "",
            oldfiles_amount = 0,
        },
        header_2 = {
            type = "text",
            oldfiles_directory = false,
            align = "center",
            fold_section = false,
            title = "Quote",
            margin = 5,
            content = {
                "To see a World in a Grain of Sand",
                "And a Heaven in a Wild Flower",
                "Hold Infinity in the palm of your hand",
                "And Eternity in an hour...",
                "",
                "                       - William Blake"
            },
            highlight = "Constant",
            default_color = "",
            oldfiles_amount = 0,
        },
        body = {
            type = "mapping",
            oldfiles_directory = false,
            align = "center",
            fold_section = false,
            title = "Basic Commands",
            margin = 5,
            content = {
                { " Find File", "Telescope find_files", "<leader>ff" },
                { " Find Word", "Telescope live_grep", "<leader>lg" },
                { " Recent Files", "Telescope oldfiles", "<leader>of" },
                { " File Browser", "Telescope file_browser", "<leader>fb" },
                { " Colorschemes", "Telescope colorscheme", "<leader>cs" },
                { " New File", "lua require'startup'.new_file()", "<leader>nf" },
            },
            highlight = "String",
            default_color = "",
            oldfiles_amount = 0,
        },
        footer = {
            type = "text",
            oldfiles_directory = false,
            align = "center",
            fold_section = false,
            title = "Footer",
            margin = 5,
            content = { "startup.nvim" },
            highlight = "Number",
            default_color = "",
            oldfiles_amount = 0,
        },

        options = {
            mapping_keys = true,
            cursor_column = 0.5,
            empty_lines_between_mappings = true,
            disable_statuslines = true,
            paddings = { 1, 3, 3, 0 },
        },
        mappings = {
            execute_command = "<CR>",
            open_file = "o",
            open_file_split = "<c-o>",
            open_section = "<TAB>",
            open_help = "?",
        },
        colors = {
            -- background = "#1f2227",
            -- folded_section = "#56b6c2",
        },
        parts = { "header", "header_2", "body", "footer" },
    },
}
