return {
    "startup-nvim/startup.nvim",
    dependencies = { "nvim-telescope/telescope.nvim", "nvim-lua/plenary.nvim" },
    opts = {
        header = {
            type = "text",
            oldfiles_directory = false,
            align = "center",
            fold_section = false,
            title = "Header",
            margin = 5,
            content = {
                   "_,    _   _    ,_",
              ".o888P     Y8o8Y     Y888o.",
             "d88888      88888      88888b",
            "d888888b_  _d88888b_  _d888888b",
            "8888888888888888888888888888888",
            "8888888888888888888888888888888",
            "YJGS8P\"Y888P\"Y888P\"Y888P\"Y8888P",
             "Y888   '8'   Y8P   '8'   888Y",
              "'8o          V          o8'",
                "`                     `",
            },
            highlight = "Statement",
            default_color = "",
            oldfiles_amount = 0,
        },
        body = {
            type = "text",
            oldfiles_directory = false,
            align = "center",
            fold_section = false,
            title = "Quote",
            margin = 5,
            content = {
                "To see a World in a Grain of Sand",
                "And a Heaven in a Wild Flower",
                "Hold Infinity in the palm of your hand",
                "And Eternity in an hour...",
                "",
                "                       - William Blake"
            },
            highlight = "Constant",
            default_color = "",
            oldfiles_amount = 0,
        },
        options = {
            mapping_keys = false,
            cursor_column = 0.5,
            empty_lines_between_mappings = true,
            disable_statuslines = true,
            paddings = { 1, 3, 3, 0 },
        },
        mappings = {
            execute_command = "<CR>",
            open_file = "o",
            open_file_split = "<c-o>",
            open_section = "<TAB>",
            open_help = "?",
        },
        colors = {
        },
        parts = { "header", "body", },
    },
}
